module.exports = {
  clothing: {
    waterproofHikingBoots: "https://bit.ly/3IJhGuN",
    bearSocks: "https://bit.ly/3AK7azV",
    rainJacket: "https://bit.ly/3QfLDod",
    fuegoJacket: "https://bit.ly/3igE9qt",
    merrellBoot: "https://bit.ly/3WVNVgq",
    alderTakeAHikeShorts: "https://bit.ly/3WS0IR6",
    alderOpenAirPants: "https://bit.ly/3jVVOEa",
    paranaZionShorts: "https://bit.ly/3WUFsu6",
    pranaBrionPants: "https://bit.ly/3itYsjY",
    altraLonePeak: "https://bit.ly/3jO2OTp",
    tevaSandal: "https://bit.ly/3QvMDqb",
  },
  camping: {
    rumpl: "https://bit.ly/3KNj54E",
  },
  hiking: {
    bearSafety: "https://www.nps.gov/subjects/bears/safety.htm",
    skimmerHydrationPack: "https://bit.ly/3aODUPx",
    trailPack: "https://bit.ly/3QbMYN8",
    nalgeneWaterBottle: "https://bit.ly/3CPU5rm",
    msrStoveKit: "https://bit.ly/3zeoqhh",
    msrStoveOnly: "https://bit.ly/3ekvAbP",
    inflatableSleepingPad: "https://bit.ly/3B8vbC2",
    trailHutTent: "https://bit.ly/3aL8n0N",
    halfDoneTent: "https://bit.ly/3AQd4zx",
    waterFilter: "https://bit.ly/3KGYfUq",
    headlamp: "https://bit.ly/3q72Sxz",
    laurenPack: "https://bit.ly/3zn4cSB",
    andersPack: "https://bit.ly/3kEpNRB",
    sleepingBag: "https://bit.ly/3xcO44A",
    flameULSleepingBag: "https://bit.ly/3Xj6Ku5",
    etherLightSleepingpadW: "https://bit.ly/3jPlnqk",
    etherLightSleepingpadM: "https://bit.ly/3VVwnQz",
    aerosPremiumPillow: "https://bit.ly/3k1jRl9",
    revelLights: "https://bit.ly/3CyvkPr",
    foamPad: "https://bit.ly/3B4E2DH",
    spork: "https://bit.ly/3DgAf8V",
    bearVault: "https://bit.ly/3B70L1Y",
    ursack: "https://bit.ly/3QFFt0R",
    electricLighter: "https://bit.ly/3xfw6hI",
    pocketRocketKit: "https://bit.ly/3VUOmGw",
    matches: "https://bit.ly/3QCGruZ",
    afterbite: "https://bit.ly/3L97NrG",
    bodyWipes: "https://bit.ly/3RueN4B",
    bugSpray: "https://bit.ly/3RGBIK3",
    toothPasteTabs: "https://bit.ly/3WSDlXz",
    firstAidKit: "https://bit.ly/3eAfPxf",
    pocketKnife: "https://bit.ly/3eEcXj2",
    greenTrailMaps: "https://bit.ly/3DhtVOp",
    blackDiamondSpikes:
      "https://www.avantlink.com/click.php?tt=el&merchant_id=e295c418-295a-447c-b265-734e25f82503&website_id=51ba0db4-8c92-4a05-8147-0a600209abbe&url=https%3A%2F%2Fwww.rei.com%2Fproduct%2F174765%2Fblack-diamond-access-spike-traction-devices&ctc=BLOG",
  },
  misc: {
    bcparksReservations: "https://camping.bcparks.ca/",
    tvp: "https://www.bobsredmill.com/tvp-textured-veg-protein.html",
    lumenaid: "luminaid.com/laurensbigadventure",
    buoyElectrolytes: "https://amzn.to/3Do9eAz",
    faceWipes: "https://go.magik.ly/ml/1lmra/",
    forerunner645: "https://amzn.to/3U0vvtU",
    powerBank: "https://amzn.to/3DivXOm",
    inflatablePillow: "https://amzn.to/3DivXOm",
    kindle: "https://amzn.to/3QwLFbz",
    squeezeBottle: "https://amzn.to/3eHLc98",
    headlamp: "https://amzn.to/3RWWchi",
    sonyA6000: "https://amzn.to/3d7uFes",
    cameraLens: "https://amzn.to/3Bbotd8",
    cameraBattery: "https://amzn.to/3RRHxE8",
    stuffSack: "https://bit.ly/3Ix9pMz",
  },
  food: {
    delicioats: "https://delicioats.com?sca_ref=2616572.Nt50VyZm5y",
    peakRefuelStroganoff: "https://bit.ly/3vK6A2Y",
  },
};
