module.exports = {
    clothing: {
        waterproofHikingBoots: "https://bit.ly/3IJhGuN",
        bearSocks: "https://bit.ly/3AK7azV",
        rainJacket: "https://bit.ly/3QfLDod",
        fuegoJacket: "https://bit.ly/3cIyTsK",
    },
    camping: {
        rumpl: "https://bit.ly/3KNj54E",
    },
    hiking: {
        bearSafety: "https://www.nps.gov/subjects/bears/safety.htm",
        skimmerHydrationPack: "https://bit.ly/3aODUPx",
        trailPack: "https://bit.ly/3QbMYN8",
        nalgeneWaterBottle: "https://bit.ly/3CPU5rm",
        msrStoveKit: "https://bit.ly/3zeoqhh",
        msrStoveOnly: "https://bit.ly/3ekvAbP",
        inflatableSleepingPad: "https://bit.ly/3B8vbC2",
        trailHutTent: "https://bit.ly/3aL8n0N",
        halfDoneTent: "https://bit.ly/3AQd4zx",
        waterFilter: "https://bit.ly/3KGYfUq",
        headlamp: "https://bit.ly/3q72Sxz",
        laurenPack: "https://bit.ly/3zn4cSB",
        andersPack: "https://bit.ly/3ILoYhC",
        sleepingBag: "https://bit.ly/3xcO44A",
        foamPad: "https://bit.ly/3B4E2DH",
        spork: "https://bit.ly/3DgAf8V",
        bearVault: "https://bit.ly/3B70L1Y",
        ursack: "https://bit.ly/3QFFt0R",
        electricLighter: "https://bit.ly/3xfw6hI",
        matches: "https://bit.ly/3QCGruZ",
        afterbite: "https://bit.ly/3L97NrG",
        bodyWipes: "https://bit.ly/3RueN4B",
        bugSpray: "https://bit.ly/3RGBIK3",
        firstAidKit: "https://bit.ly/3eAfPxf",
        pocketKnife: "https://bit.ly/3eEcXj2",
        greenTrailMaps: "https://bit.ly/3DhtVOp",
    },
    misc: {
        bcparksReservations: "https://camping.bcparks.ca/",
        tvp: "https://www.bobsredmill.com/tvp-textured-veg-protein.html",
        lumenaid: "luminaid.com/laurensbigadventure",
        buoyElectrolytes: "https://amzn.to/3Do9eAz",
        faceWipes: "https://go.magik.ly/ml/1lmra/",
        forerunner645: "https://amzn.to/3U0vvtU",
        powerBank: "https://amzn.to/3DivXOm",
        inflatablePillow: "https://amzn.to/3DivXOm",
        kindle: "https://amzn.to/3QwLFbz",
        squeezeBottle: "https://amzn.to/3eHLc98",
        headlamp: "https://amzn.to/3RWWchi",  
        sonyA6000: "https://amzn.to/3d7uFes",
        cameraLens: "https://amzn.to/3Bbotd8",
        cameraBattery: "https://amzn.to/3RRHxE8",
    }
}
