#!/bin/bash

# Batch resize and watermark images in a directory
# Requires ImageMagick : https://imagemagick.org/

TARGET_DIR="$1"
ANNOTATION='(C) TrailsAndTrekking.com'
MAX_PIXELS=426410

if [[ -z "$TARGET_DIR" ]]; then
  TARGET_DIR="."
fi

TO_CONVERT="$(find $TARGET_DIR -type f |egrep '.*(png|PNG|jpg|JPG|jpeg|JPEG)$')"

for file in $TO_CONVERT; do
  echo "Updating image: $file"
  convert $file -resize ${MAX_PIXELS}'@' $file

  echo "Annotating $file with watermark"
  convert $file -gravity SouthEast \
    -stroke '#000C' -strokewidth 2 -annotate 0 "$ANNOTATION" \
    -stroke none -fill white -annotate 0 "$ANNOTATION" $file
done